version: '3.8'

services:
   sgp:
      image: sgp/erikSena:1.0
      networks:
        - backend
      environment:
        #- DomainConnectionString=
        #- RedisConnectionString=redis
        - ASPNETCORE_ENVIRONMENT=Development
      ports: 
         - "5000:80"
   
networks:
  backend:

 